### ISSUE TITLE
 Impossible de désélectionner une lettre

### ISSUE THREAD

**Issue by sibylassana95** [Devdiop221/baat_bi#1]
**Problème :**
J''ai remarqué un problème assez gênant : une fois qu'on sélectionne une lettre dans la grille, **impossible de la désélectionner si on se trompe**. Ça bloque un peu le jeu, surtout quand on fait une erreur ou qu'on veut changer de sélection.

**Suggestions de résolution :**

Ajouter une logique permettant de désélectionner une lettre lorsqu'elle est cliquée à nouveau.

**Comment by Devdiop221** [comment]
Merci beaucoup @sibylassana95 pour la suggestion.
Je l'avais oublié quand je faisais le onboard , et c'est frustrant s'il bloque le jeu.
